name: Update Production Repository 
on:
  push:
    branches:
      - main

jobs:
  update-prod-repo:
    if: github.repository == 'quallifica-tech/caodominio'
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      
      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_CAODOMINIO }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to production repository
        run: |
          git remote add production git@github.com:caodominio/ong-manager.git
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          git push production main:main --force