name: Update Production Repository 
on:
  push:
    branches:
      - main


jobs:
  update-prod-repo:
    if: github.repository == 'quallifica-tech/caodominio'
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write 

    steps: 
      - uses: actions/checkout@v3
      - name: Push to production repository
        env:
          TOKEN: ${{ secrets.PROD_REPO_TOKEN }}
        run: |
          git remote add production https://oauth2:${TOKEN}@github.com/caodominio/ong-manager.git
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          git push production main:main --force