name: Update Production Repository 
on:
  push:
    branches:
      - main

jobs:
  update-prod-repo:
    if: github.repository == 'quallifica-tech/caodominio'
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      
      - name: Set up SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SSH_CAODOMINIO }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add /home/runner/.ssh/github_actions

      - name: Push to production repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git remote add production git@github.com:caodominio/ong-manager.git
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          git push production main:main --force